name: XautralFunctions
version: 1.0-SNAPSHOT
main: com.xautral.xautralfunctions.XautralFunctions
api-version: '26.2'
author: TenoSrv
description: Sistema avanzado de funciones para servidores
commands:
  xautral:
    description: Comando principal de XautralFunctions
    usage: /xautral <composer|trade|villagerattack|tps>
    permission: xautral.composer
    aliases: [xau, xautralfunctions, xf]
permissions:
  xautral.composer:
    default: op
  xautral.op:
    default: op
    description: Permite editar trades de aldeanos con shift+click derecho y usar comandos avanzados
