name: MiniFuncPlugin
version: 1.0-SNAPSHOT
main: com.minifunc.minifuncplugin.MiniFuncPlugin
api-version: '26.2'
author: TenoSrv
description: Formato de texto y secuenciador de sonidos de bloques de notas
commands:
  minifunc:
    description: Abre el compositor de MiniFunc
    usage: /minifunc composer [composition]
    permission: minifunc.composer
permissions:
  minifunc.composer:
    default: op
