name: PermaDeathPlugin
version: 1.0-SNAPSHOT
main: com.permadeath.permadeathplugin.PermaDeathPlugin
api-version: 1.20
author: Xautral/OmniXautral
description: Plugin de permadeath para Minecraft

commands:
  permaedeath:
    description: Activa/desactiva el modo permadeath
    usage: /permaedeath <on|off>
    aliases: [perma, pd]
    permission: permadeath.admin

permissions:
  permadeath.admin:
    description: Permite administrar el modo permadeath
    default: op
