name: SkillWeaponsPlugin
version: 1.0-SNAPSHOT
main: com.skillweapons.skillweaponsplugin.SkillWeaponsPlugin
api-version: '26.2'
author: Xautral/OmniXautral
description: Plugin de skills para armas en Minecraft

commands:
  sw:
    description: Comandos de SkillWeapons
    usage: /sw give [enchant]
    aliases: [skillweapons, skillw]
    permission: skillweapons.admin

permissions:
  skillweapons.admin:
    description: Permite usar comandos de SkillWeapons
    default: op